### ISSUE TITLE
ROR metadata viewer shows only one parent

### ISSUE THREAD

**Issue by matdillen** [arthurpsmith/extendror#9]
Compare:

https://extendror.toolforge.org/extension/05qrfxd25/02azz6x90
and
https://api.ror.org/organizations/02azz6x90

It does show them all in the Wikidata viewer:

https://extendror.toolforge.org/wikidata/05qrfxd25/Q4201751

**Comment by arthurpsmith** [comment]
This is fixed with the latest update - thanks for pointing out the problem!
